// AUTO-GENERATED by scripts/process-assets.mjs — do not edit by hand.
export interface MediaItem {
  id: string
  src: string
  w: number
  h: number
  alt: string
  credit: 'user'
}

export const MEDIA: MediaItem[] = [
  {
    "id": "hero-portrait",
    "src": "images/hero-portrait.webp",
    "w": 400,
    "h": 500,
    "alt": "Studio portrait of Sean O'Malley with braids and face tattoos",
    "credit": "user"
  },
  {
    "id": "main-poster",
    "src": "images/main-poster.webp",
    "w": 516,
    "h": 387,
    "alt": "Duotone pink and purple poster of Sean O'Malley raising both fists",
    "credit": "user"
  },
  {
    "id": "octagon-arms",
    "src": "images/octagon-arms.webp",
    "w": 408,
    "h": 234,
    "alt": "Sean O'Malley arms spread wide in the octagon with red braids",
    "credit": "user"
  },
  {
    "id": "collage",
    "src": "images/collage.webp",
    "w": 800,
    "h": 450,
    "alt": "Pink and green paint-splash collage of Sean O'Malley",
    "credit": "user"
  },
  {
    "id": "celebrate-alt",
    "src": "images/celebrate-alt.webp",
    "w": 408,
    "h": 234,
    "alt": "Sean O'Malley celebrating in the octagon",
    "credit": "user"
  },
  {
    "id": "praying-cutout",
    "src": "images/praying-cutout.webp",
    "w": 534,
    "h": 707,
    "alt": "Cutout of Sean O'Malley praying with rainbow braids and UFC gloves",
    "credit": "user"
  },
  {
    "id": "fight-stance",
    "src": "images/fight-stance.webp",
    "w": 387,
    "h": 516,
    "alt": "Sean O'Malley in a fighting stance with red gloves and pink and blue braids",
    "credit": "user"
  },
  {
    "id": "teal-portrait",
    "src": "images/teal-portrait.webp",
    "w": 484,
    "h": 634,
    "alt": "Portrait of Sean O'Malley with teal braids and pink UFC shorts in the octagon",
    "credit": "user"
  },
  {
    "id": "walkout-jacket",
    "src": "images/walkout-jacket.webp",
    "w": 736,
    "h": 1261,
    "alt": "Sean O'Malley in a hooded UFC walkout jacket under arena lights",
    "credit": "user"
  },
  {
    "id": "pink-zebra",
    "src": "images/pink-zebra.webp",
    "w": 408,
    "h": 612,
    "alt": "Sean O'Malley in pink zebra suit with USA flags",
    "credit": "user"
  },
  {
    "id": "screaming-chest",
    "src": "images/screaming-chest.webp",
    "w": 768,
    "h": 512,
    "alt": "Sean O'Malley screaming with pink braids and chest tattoo",
    "credit": "user"
  },
  {
    "id": "screaming-chest-alt",
    "src": "images/screaming-chest-alt.webp",
    "w": 500,
    "h": 333,
    "alt": "Sean O'Malley screaming (alternate angle)",
    "credit": "user"
  },
  {
    "id": "cage-look",
    "src": "images/cage-look.webp",
    "w": 497,
    "h": 335,
    "alt": "Sean O'Malley in the cage looking away",
    "credit": "user"
  },
  {
    "id": "close-braids",
    "src": "images/close-braids.webp",
    "w": 492,
    "h": 320,
    "alt": "Sean O'Malley looking down with multi-color braids",
    "credit": "user"
  },
  {
    "id": "champion-belt",
    "src": "images/champion-belt.webp",
    "w": 415,
    "h": 737,
    "alt": "Sean O'Malley standing in octagon with championship belt",
    "credit": "user"
  },
  {
    "id": "rainbow-collage",
    "src": "images/rainbow-collage.webp",
    "w": 494,
    "h": 619,
    "alt": "Neon rainbow collage of Sean O'Malley",
    "credit": "user"
  },
  {
    "id": "walkout-belt",
    "src": "images/walkout-belt.webp",
    "w": 399,
    "h": 501,
    "alt": "Sean O'Malley walking out with championship belt",
    "credit": "user"
  },
  {
    "id": "wineland-uppercut",
    "src": "images/wineland-uppercut.webp",
    "w": 340,
    "h": 239,
    "alt": "Sean O'Malley landing an uppercut on Eddie Wineland in the octagon",
    "credit": "user"
  }
]

export const mediaById = (id: string): MediaItem | undefined => MEDIA.find((m) => m.id === id)
